# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a440076bc0d7765be0521f45c67f3b8c6d511ca35711e5e99c02000891646889c0ecd1f0999042b0f893ea9804bfbbc4e3fbc136624c2449399f88ab78320ef2

test:
  secret_key_base: 82bd1e278cea0c7b22d1e324c2fa7993ec4bb3d183dba9e42b5abb7efb98d6d6412855dad3ac5707dd801acbf237f5107859934bc6af3e42c5d752ba4e287db1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
